packages:
  - '.'

allowBuilds:
  '@tailwindcss/oxide': true
  '@vercel/speed-insights': true
  esbuild: true
  protobufjs: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - core-js-pure
  - esbuild
  - protobufjs
  - sharp
  - unrs-resolver
