blank_issues_enabled: false
contact_links:
  - name: Neverland Money Community Support
    url: https://discord.gg/neverland-money
    about: Please ask and answer questions about Neverland Money here
